#!/usr/bin/env bash
# This script configures a server as a load balancer using HAproxy

# Update package lists and install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy for round-robin load balancing
cat <<EOL | sudo tee /etc/haproxy/haproxy.cfg > /dev/null
global
    log /dev/log local0
    log /dev/log local1 notice
    maxconn 2000
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 446006-web-01 54.237.48.69:80 check
    server 446006-web-02 54.173.198.171:80 check
EOL

# Enable HAProxy service to start on boot
sudo systemctl enable haproxy

# Start HAProxy service
sudo systemctl start haproxy

# Allow HAProxy traffic through the firewall (if firewall is enabled)
sudo ufw allow 80/tcp

# Print HAProxy status
# sudo systemctl status haproxy

# Restart the haproxy service
sudo service haproxy restart
