#!/usr/bin/env bash
# Manages the script manage_my_process.
#   When passed the argument `start`:
#     1. Starts manage_my_process
#     2. Creates a file containings its PID in /var/run/my_process.pid
#     3. Displays "manage_my_process started"
#   When passed the argument `stop`:
#     1. Stops manage_my_process
#     2. Deletes the file /var/run/my_process.pid
#     3. Displays "manage_my_process stopped"
#   When passed the argument `restart`:
#     1. Stops manage_my_process
#     2. Deletes the file /var/run/my_process.pid
#     3. Starts manage_my_process
#     4. Creates a file containing its PID in /var/run/my_process.pid
#     5. Displays "manage_my_process restarted"
#   If any other or no arguments are passed, displays
#+  "Usage: manage_my_process {start|stop

argv1=$1
tmpfile="/var/run/my_process.pid"

startLoop_n_createFile()
{
    ./manage_my_process &
    echo "$!" > "$tmpfile"
}
killLoop_n_rmFile()
{
    #kill "$(cat "$tmpfile")"
    sudo pkill -f "./manage_my_process"
    rm "$tmpfile"
}
case "$argv1" in
    start) echo "manage_my_process started"
	startLoop_n_createFile
	;;
    stop) echo "manage_my_process stopped"
	killLoop_n_rmFile
	;;
    restart) echo "manage_my_process restarted"
	killLoop_n_rmFile
	startLoop_n_createFile
	;;
    *) echo "Usage: manage_my_process {start|stop|restart}"
	;;
esac
