#!/usr/bin/env bash
# Configures a ufw firewall to block all incoming traffic
#+ except for TCP ports 22, 443, and 80.

# Ensure the script is executed with root privileges
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Install UFW
apt-get install -y ufw

# Enable IPv6 in UFW configuration
sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw

# Disable and enable UFW to apply configurations
ufw disable
ufw enable

# Set default policies
ufw default deny incoming
ufw default allow outgoing

# Allow specific TCP ports
ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp

# Reload UFW to apply changes
ufw reload

# Display UFW status
ufw status verbose

